- name: Setup User & Group
  hosts: all
  become: true
  tasks:
    - name: create Group
      group:
        name: pager_forwarding
        state: present
    - name: create User
      user:
        name: pager_forwarding
        groups: pager_forwarding
        shell: /sbin/nologin
        append: yes
        state: present
        create_home: no
- name: Setup files
  hosts: all
  become: true
  tasks:
  - name: Copy systemd service file to server
    copy:
      src: resources/pager-forwarding.service
      dest: /etc/systemd/system
      owner: root
      group: root
  - name: Create Directory
    file:
      path: /usr/local/pager-forwarding
      state: directory
      mode: '0755'
  - name: Download Compiled Service
    get_url:
      url: https://github.com/mathias-mueller/pager-relais-forwarding/releases/download/latest/pager-relais-forwarding_arm
      dest: /usr/pager-forwarding/main
      mode: '0777'
  - name: Copy Config
    ansible.builtin.copy:
      src: deployments/resources/config.ini
      dest: /usr/local/pager-forwarding/config.ini
      owner: root
      group: root
  - name: Copy Message file
    ansible.builtin.copy:
      src: deployments/resources/message.txt
      dest: /usr/local/pager-forwarding/message.txt
      owner: root
      group: root
- name: Start
  hosts: all
  become: true
  tasks:
  - name: Start Service
    ansible.builtin.systemd:
      name: pager_forwarding
      state: started
      enabled: yes