---
- name: create Group
  group:
    name: pager_forwarding
    state: present

- name: create User
  user:
    name: pager_forwarding
    groups: pager_forwarding
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Copy systemd service file to server
  copy:
    src: resources/pager-forwarding.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Service

- name: Download Compiled Service
  ansible.builtin.get_url:
    url: http://example.com/path/file.conf
    dest: /usr/pager-forwarding/main
    mode: '0777'
  notify:
    - Start Service

- name: Copy Config
  copy:
    src: deployments/resources/config.ini
    dest: /usr/local/pager-forwarding/build/config.ini
    owner: root
    group: root
  notify:
    - Start Service

- name: Copy Message file
  copy:
    src: deployments/resources/message.txt
    dest: /usr/local/pager-forwarding/build/message.txt
    owner: root
    group: root
  notify:
    - Start Service

---
- name: Start Service
  systemd:
    name: pager_forwarding
    state: started
    enabled: yes