- name: Download Prometheus
  hosts: all
  tasks:
    - name: Create tmp dir
      ansible.builtin.file:
        path: /tmp/prometheus
        state: directory
    - name: Create Prometheus dir
      ansible.builtin.file:
        path: /usr/local/prometheus
        state: directory
    - name: Download Tar
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-armv7.tar.gz
        dest: /tmp/prometheus
        remote_src: true
    - name: Copy files
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/prometheus/prometheus-2.22.0.linux-armv7
        dest: /usr/local/prometheus
    - name: Remove temp
      ansible.builtin.file:
        path: /tmp/prometheus
        state: absent
- name: Setup Service
  hosts: all
  tasks:
    - name: Copy Prometheus Service file
      ansible.builtin.copy:
        src: resources/prometheus.service
        dest: /etc/systemd/system
    - name: Start Prometheus Service
      ansible.builtin.service:
        name: prometheus
        state: restarted
        enabled: true
