- name: Download Node Exporter
  hosts: all
  become: true
  tasks:
    - name: Create tmp dir
      ansible.builtin.file:
        path: /tmp/prometheus-node-exporter
        state: directory
        mode: '0755'
    - name: Create Node Exporter dir
      ansible.builtin.file:
        path: /usr/local/prometheus-node-exporter
        state: directory
        mode: '0755'
    - name: Download Tar
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-armv7.tar.gz
        dest: /tmp/prometheus-node-exporter
        remote_src: true
    - name: Copy files
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/prometheus-node-exporter/node_exporter-1.4.0.linux-armv7/
        dest: /usr/local/prometheus-node-exporter
        mode: '0777'
    - name: Remove temp
      ansible.builtin.file:
        path: /tmp/prometheus-node-exporter
        state: absent
- name: Setup Service
  hosts: all
  become: true
  tasks:
    - name: Create Node Exporter User
      ansible.builtin.user:
        name: prometheus-node-exporter
        groups: pi
        shell: /sbin/nologin
        append: true
        state: present
        create_home: false
    - name: Copy Node Exporter Service file
      ansible.builtin.copy:
        src: resources/prometheus-node-exporter.service
        dest: /etc/systemd/system
        mode: '0777'
    - name: Start Node Exporter Service
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: restarted
        enabled: true
