name: Ansible Lint
on:
  push:
    paths:
      - deployments/**
      - .github/workflows/ansible_lint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "deployments/"