name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: ['amd64'] #, 'arm', 'arm64', 'armv7l']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: "Version"
        run: go version
      - name: Build
        run: env GOOS=linux GOARCH=${{matrix.os}} go build -o pager-relais-forwarding_{{matrix.os}} cmd/main/main.go
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            pager-relais-forwarding_{{matrix.os}}
          
          

