name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: ['amd64'] #, 'arm', 'arm64', 'armv7l']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: "Version"
        run: go version
      - name: Build
        run: env GOOS=linux GOARCH=${{matrix.os}} go build -o pager-relais-forwarding_{{matrix.os}} cmd/main/main.go
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
         draft: false
         prerelease: false
         release_name: ${{ github.ref }}
         tag_name: ${{ github.ref }}
        env:
         GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pager-relais-forwarding_{{matrix.os}}
          asset_name: pager-relais-forwarding_{{matrix.os}}
          
          

